name: deploy-release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  NODE_VERSION: '24.11.0'

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Node.js version LTS and setup cache
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies for project
        run: npm install

      - name: Lint TypeScript and ESLint
        run: npm run lint:eslint && npm run lint:ts

      - name: Deploy PR (main) for new Release
        uses: googleapis/release-please-action@v5
        with:
          release-type: node
          target-branch: main
          config-file: 'release-please-config.json'
          token: ${{ secrets.PAT }}
